#!/bin/sh

# Default settings:
alias \
    cp='cp -iv' \
    mv='mv -iv' \
    rm='rm -v' \
    mkdir='mkdir -pv' \
    ll='exa -Flag --git --colour=always --time-style=long-iso --group-directories-first' \
    grep='grep --color=auto' \
    diff='diff --color=auto'

# Abbreviations:
alias \
    c='cd ..' \
    e='emacsclient -cn' \
    v='nvim' \
    o='xdg-open' \
    ka='killall' \
    sc='shellcheck' \
    spt='speedtest-cli' \
    yt='youtube-viewer' \
    p='sudo pacman' \
    pn='sudo pacman --needed' \
    psyu='sudo pacman -Syu --ignore=linux'
    # ^ This is done because later versions of the kernel break support
    # for my HUION tablet. Need to check from time to time if it's fixed.

# Git:
alias \
    g='git' \
    gs='git status' \
    gd='git diff' \
    ga='git add' \
    gc='git commit' \
    gcm='git commit -m' \
    gca='git commit --amend' \
    gpushom='git push origin master' \
    gpullom='git pull origin master'
